version: '3.6'

services:
  tailscale:
    privileged: true
    network_mode: "host"
    container_name: tailscale
    image: tailscale/tailscale:${TAILSCALE_VERSION}
    restart: unless-stopped
    environment:
      # - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ${DATA_PATH}:/var/lib/tailscale
    cap_add:                              # Required for tailscale to work
        - net_admin
        - sys_module
    command: tailscaled